# Generated by Django 4.1.3 on 2023-05-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_post_yildiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evsahibi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.profil'),
        ),
    ]
