# Generated by Django 4.1.3 on 2023-05-05 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0008_alter_post_evsahibi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evsahibi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
